

- Ruby 异常是一个对象，是类 Exception 的实例或该类的后代
- 在 Ruby 程序中, 当出现问题时，它会抛出异常行为, 默认情况下, Ruby 程序在引发异常时终止
- 我们可以在 Ruby 中声明一些异常处理程序。异常处理程序是当其他代码块中发生异常时执行的代码块
- 异常以两种方式处理
	- 终止程序
	- 处理异常：提供救援条款，使程序控制流向救援子句
- 全局变量`$!`包含当前异常，`$@`包含当前异常的回溯
- 在 Ruby 异常层次结构中，大多数子类扩展了类 StandardError

###  ###


# 1.异常 #

异常的内置子类如下：

- NoMemoryError - 无内存错误
- ScriptError - 脚本错误
- SecurityError - 安全错误
- SignalException - 信号异常
- StandardError - 标准错误
- SystenExit - 系统退出
- SystemStackError - 系统堆栈错误
- fatal - impossible to rescue： 致命 - 无法救援

`raise("<提示字符串>")`：自己抛出错误`RuntimeError`

# 2.处理异常 #

使用`rescue`子句，位于代码块末尾和`end`之间

!!! tip
	- 好像不支持不带有后面`end`的代码(如全局区域)
	- 处理异常后，不会恢复代码块内发生异常之后, `end`之前的语句
	- 支持多个`rescue`，`else`子句

# 3.异常对象 #

```rb
begin
  d = 0/0
rescue ZeroDivisionError => e
  puts "Exception Class: #{ e.class.name }"
  puts "Exception Message: #{ e.message }"
  puts "Exception Backtrace: #{ e.backtrace }"
end
```

![](https://pic.peo.pw/a/2023/02/05/63df2756278b7.png)

# 4.retry语句 #

`retry`使控制流回溯到`begin`之后(注意：并不是回溯到发生异常之后)

```rb
a = b = 0
begin
  puts "a"
  d = a/b
  puts "b"
rescue
  puts "c"
  b = 1
  retry 
  puts "d"
end
```

![](https://pic.peo.pw/a/2023/02/05/63df2882ebfb5.png)

# 5.raise语句 #

- `raise` - 重新引发当前异常
- `raise("<错误消息>")` - 创建一个`RuntimeError`错误，然后，在调用堆栈中引发此异常
- `raise(<异常类型>, "<错误消息>")` - 创建特定异常
- `raise(<异常类型>, "<错误消息>" condition)`

# 6.ensure语句 #

`ensure`子句位于`rescue`子句之后，无论是否发生异常都会执行`ensure`子句

# 7.else语句 #

`else`子句在`rescue`子句之后，`ensure`子句之前

# 8.Throw&Catch #

- `throw`和`catch`子句的关系类似于`raise`和`rescue`子句，并且比后者块
- 不同点是前者以标签的形式


